# 1.Importing of libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import accuracy_score, confusion_matrix
import pickle

# 2.Importing dataset

In [2]:
dataset=pd.read_csv("Avalanche.csv")
dataset

Slope Forest Density  Snow Density  Air Temperature  Wind  Prediction
0       59              H            52              -17    19           2
1       24              L            23               -8    19           0
2       15              H            30                7    19           0
3       27              L            61              -13    25           1
4       34              H             4              -20     7           0
5       34              L            76               -7    40           1
6       34              M            73              -32    27           2
7       34              L             4                3     9           1
8       34              M            44                6     6           0
9       34              L            73              -34    13           2
10      34              M            33               13    35           1
11      34              L            51               -4    35           1
12      34              M            59              -29     8           2
13      34              L            64              -21    10           2
14      34              L            76              -27    38           2
15      34              H             2              -23    33           2
16      75              L            70              -11    36           2
17      36              H            43                2    37           1
18      48              L            55               15    19           1
19      29              M            11              -25    38           0
20      59              H            27              -27     6           1
21      48              M            32                8    40           1
22      17              M            15               -2    36           0
23      18              M            31               -4    35           0
24      60              M            58               15     9           2
25      28              H            70              -11    10           1
26      21              M            70              -27     8           1
27      79              M             2               13    27           2
28      52              H            35              -18    13           2
29      61              H            67              -30     9           1
..     ...            ...           ...              ...   ...         ...
174     22              H            48              -14    17           0
175     74              M            68               -4    39           2
176     50              M             3              -20    11           1
177     71              L            46              -24    10           2
178     22              L            13              -22    39           0
179     80              H            16              -14     7           2
180     66              L            78               -7    22           2
181     76              M            52               11    11           1
182     18              M            39               12     7           0
183     44              M            10              -34    37           0
184     69              H            54               11    29           1
185     59              L             6               10    37           0
186     74              H            36              -22    12           1
187     55              H            24              -16    16           1
188     22              H            48              -14    17           0
189     74              M            68               -4    39           2
190     50              M             3              -20    11           1
191     71              L            46              -24    10           2
192     22              L            13              -22    39           0
193     15              H            30                7    19           0
194     27              L            61              -13    25           1
195     34              H     

# Splitting Dataset in to Independent variable and Dependent variable

First,We have to split the independent and dependent variables to perform further operations

In [3]:
x=dataset.iloc[:,0:5].values
x

array([[59, 'H', 52, -17, 19],
       [24, 'L', 23, -8, 19],
       [15, 'H', 30, 7, 19],
       ...,
       [34, 'M', 33, 13, 35],
       [34, 'L', 51, -4, 35],
       [34, 'M', 59, -29, 8]], dtype=object)

In [4]:
y=dataset.iloc[:,5:].values
y

array([[2],
       [0],
       [0],
       [1],
       [0],
       [1],
       [2],
       [1],
       [0],
       [2],
       [1],
       [1],
       [2],
       [2],
       [2],
       [2],
       [2],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [2],
       [1],
       [1],
       [2],
       [2],
       [1],
       [1],
       [2],
       [1],
       [2],
       [0],
       [2],
       [1],
       [2],
       [2],
       [2],
       [1],
       [2],
       [1],
       [2],
       [1],
       [0],
       [1],
       [2],
       [0],
       [1],
       [2],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [2],
       [2],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [2],
       [1],
       [2],
       [0],
       [1],
       [1],
       [2],
       [0],
       [2],
       [0],
       [0],
       [1],
       [1],
       [2],
       [1],
    

# 5.Label Encoding

In [5]:
data=dataset['Forest Density'].value_counts()
points=data.index
points

Index(['L', 'M', 'H'], dtype='object')

In [6]:
data=dataset['Forest Density'].value_counts()
data

L    76
M    66
H    62
Name: Forest Density, dtype: int64

In [7]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()

In [8]:
x[:,1]

array(['H', 'L', 'H', 'L', 'H', 'L', 'M', 'L', 'M', 'L', 'M', 'L', 'M',
       'L', 'L', 'H', 'L', 'H', 'L', 'M', 'H', 'M', 'M', 'M', 'M', 'H',
       'M', 'M', 'H', 'H', 'L', 'M', 'M', 'L', 'L', 'L', 'H', 'L', 'L',
       'L', 'L', 'L', 'H', 'M', 'L', 'H', 'H', 'M', 'M', 'M', 'M', 'L',
       'H', 'M', 'H', 'H', 'L', 'M', 'H', 'L', 'M', 'M', 'M', 'H', 'L',
       'H', 'H', 'H', 'M', 'M', 'L', 'L', 'L', 'H', 'M', 'H', 'L', 'M',
       'M', 'H', 'L', 'L', 'M', 'L', 'H', 'H', 'L', 'M', 'L', 'H', 'H',
       'M', 'M', 'L', 'L', 'H', 'M', 'L', 'L', 'H', 'L', 'H', 'L', 'H',
       'L', 'M', 'L', 'M', 'L', 'M', 'L', 'M', 'L', 'L', 'H', 'L', 'H',
       'L', 'M', 'H', 'M', 'H', 'L', 'H', 'L', 'H', 'L', 'M', 'L', 'M',
       'L', 'M', 'L', 'M', 'L', 'L', 'H', 'L', 'H', 'L', 'M', 'H', 'M',
       'H', 'H', 'L', 'M', 'H', 'L', 'M', 'M', 'M', 'H', 'L', 'H', 'H',
       'H', 'M', 'M', 'L', 'L', 'L', 'H', 'M', 'H', 'H', 'L', 'M', 'M',
       'M', 'H', 'L', 'H', 'H', 'H', 'M', 'M', 'L', 'L', 'H', 'L

In [9]:
x[:,1]=lb.fit_transform(x[:,1])
x

array([[59, 0, 52, -17, 19],
       [24, 1, 23, -8, 19],
       [15, 0, 30, 7, 19],
       ...,
       [34, 2, 33, 13, 35],
       [34, 1, 51, -4, 35],
       [34, 2, 59, -29, 8]], dtype=object)

# 6.One Hot Encoding

In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer([("on",OneHotEncoder(),[1])],remainder="passthrough")
x=ct.fit_transform(x)
x

C:\Users\GLOBAL\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


array([[1.0, 0.0, 0.0, ..., 52, -17, 19],
       [0.0, 1.0, 0.0, ..., 23, -8, 19],
       [1.0, 0.0, 0.0, ..., 30, 7, 19],
       ...,
       [0.0, 0.0, 1.0, ..., 33, 13, 35],
       [0.0, 1.0, 0.0, ..., 51, -4, 35],
       [0.0, 0.0, 1.0, ..., 59, -29, 8]], dtype=object)

In [11]:
x=x[:,1:]
x

array([[0.0, 0.0, 59, 52, -17, 19],
       [1.0, 0.0, 24, 23, -8, 19],
       [0.0, 0.0, 15, 30, 7, 19],
       ...,
       [0.0, 1.0, 34, 33, 13, 35],
       [1.0, 0.0, 34, 51, -4, 35],
       [0.0, 1.0, 34, 59, -29, 8]], dtype=object)

# 8.Splitting Data Into Train and Test

Firstly,We have to split the data into Train and Test to perform Feature Scaling

In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.1,random_state=0)

In [13]:
x_train

array([[0.0, 1.0, 16, 68, 10, 26],
       [0.0, 0.0, 69, 54, 11, 29],
       [1.0, 0.0, 34, 76, -27, 38],
       ...,
       [1.0, 0.0, 48, 55, 15, 19],
       [0.0, 1.0, 69, 29, 15, 15],
       [0.0, 0.0, 74, 36, -22, 12]], dtype=object)

In [14]:
y_train

array([[0],
       [1],
       [2],
       [1],
       [1],
       [0],
       [0],
       [1],
       [2],
       [2],
       [1],
       [2],
       [2],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [2],
       [0],
       [1],
       [0],
       [0],
       [0],
       [2],
       [2],
       [2],
       [0],
       [2],
       [2],
       [2],
       [1],
       [0],
       [1],
       [0],
       [2],
       [0],
       [2],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [2],
       [2],
       [2],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [2],
       [0],
       [0],
       [2],
       [1],
       [2],
       [2],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [2],
       [1],
       [2],
       [2],
       [2],
    

In [15]:
x_test

array([[1.0, 0.0, 48, 55, 15, 19],
       [0.0, 0.0, 26, 12, -8, 17],
       [1.0, 0.0, 61, 17, -11, 9],
       [1.0, 0.0, 80, 73, 14, 35],
       [0.0, 1.0, 34, 33, 13, 35],
       [0.0, 0.0, 50, 5, -31, 7],
       [1.0, 0.0, 34, 76, -7, 40],
       [1.0, 0.0, 27, 61, -13, 25],
       [0.0, 1.0, 34, 59, -29, 8],
       [1.0, 0.0, 59, 6, 10, 37],
       [0.0, 1.0, 18, 39, 12, 7],
       [0.0, 0.0, 55, 24, -16, 16],
       [1.0, 0.0, 66, 78, -7, 22],
       [1.0, 0.0, 22, 13, -22, 39],
       [0.0, 0.0, 55, 24, -16, 16],
       [1.0, 0.0, 34, 4, 3, 9],
       [0.0, 1.0, 34, 44, 6, 6],
       [0.0, 1.0, 34, 33, 13, 35],
       [0.0, 0.0, 38, 1, -14, 31],
       [0.0, 0.0, 55, 24, -16, 16],
       [1.0, 0.0, 18, 21, -11, 23]], dtype=object)

In [16]:
y_test

array([[1],
       [0],
       [2],
       [2],
       [1],
       [1],
       [1],
       [1],
       [2],
       [0],
       [0],
       [1],
       [2],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1]], dtype=int64)

# 7.Feature Scaling

To perform feature scaling we must perform any one type of Encoding(Label or One Hot)

In [17]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [18]:
x

array([[0.0, 0.0, 59, 52, -17, 19],
       [1.0, 0.0, 24, 23, -8, 19],
       [0.0, 0.0, 15, 30, 7, 19],
       ...,
       [0.0, 1.0, 34, 33, 13, 35],
       [1.0, 0.0, 34, 51, -4, 35],
       [0.0, 1.0, 34, 59, -29, 8]], dtype=object)

# Model Building

# Training And Testing The Model

We used Decision Tree Classifier to Training and Testing the model

In [19]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier(random_state=0,criterion='gini')
dt.fit(x_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=0, splitter='best')

In [20]:
y_predict=dt.predict(x_test)
y_predict

array([1, 2, 2, 2, 1, 1, 1, 1, 2, 0, 0, 1, 2, 0, 1, 1, 0, 1, 0, 1, 0],
      dtype=int64)

In [21]:
y_test

array([[1],
       [0],
       [2],
       [2],
       [1],
       [1],
       [1],
       [1],
       [2],
       [0],
       [0],
       [1],
       [2],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1]], dtype=int64)

# Model Evaluation

We can predict the output by giving some values

In [22]:
dt.predict([[1.0,0.0,54,24,15,19]])

array([1], dtype=int64)

In [23]:
accuracy=accuracy_score(y_test,y_predict)
print("Accuracy of the model:", accuracy)

Accuracy of the model: 0.9047619047619048


So,After using Decision Tree Classifier we got 90% Accuracy